// Auto-generated by preprocess.py — do not edit
const MAP_CONFIG = {
  "Badlands": {
    "extent": 3000,
    "image_size": 4096,
    "factions": [
      "Sol",
      "Cent"
    ],
    "scan_min_x": -3000,
    "scan_max_x": 3000,
    "scan_min_z": -3000,
    "scan_max_z": 3000,
    "scan_step": 15,
    "grid_w": 401,
    "grid_h": 401
  },
  "CrimsonPeak": {
    "extent": 2048,
    "image_size": 4096,
    "factions": [
      "Sol",
      "Cent"
    ],
    "scan_min_x": -2040,
    "scan_max_x": 2040,
    "scan_min_z": -2040,
    "scan_max_z": 2040,
    "scan_step": 15,
    "grid_w": 273,
    "grid_h": 273
  },
  "CrystalChasm": {
    "extent": 1500,
    "image_size": 4096,
    "factions": [
      "Sol",
      "Cent"
    ],
    "scan_min_x": -1500,
    "scan_max_x": 1500,
    "scan_min_z": -1500,
    "scan_max_z": 1500,
    "scan_step": 15,
    "grid_w": 201,
    "grid_h": 201
  },
  "GreatErg": {
    "extent": 3000,
    "image_size": 4096,
    "factions": [
      "Sol",
      "Cent"
    ],
    "scan_min_x": -3000,
    "scan_max_x": 3000,
    "scan_min_z": -3000,
    "scan_max_z": 3000,
    "scan_step": 15,
    "grid_w": 401,
    "grid_h": 401
  },
  "NarakaCity": {
    "extent": 3000,
    "image_size": 4096,
    "factions": [
      "Sol",
      "Cent"
    ],
    "scan_min_x": -3000,
    "scan_max_x": 3000,
    "scan_min_z": -3000,
    "scan_max_z": 3000,
    "scan_step": 15,
    "grid_w": 401,
    "grid_h": 401
  },
  "NorthPolarCap": {
    "extent": 2048,
    "image_size": 4096,
    "factions": [
      "Sol",
      "Cent"
    ],
    "scan_min_x": -2040,
    "scan_max_x": 2040,
    "scan_min_z": -2040,
    "scan_max_z": 2040,
    "scan_step": 15,
    "grid_w": 273,
    "grid_h": 273
  },
  "RiftBasin": {
    "extent": 1500,
    "image_size": 4096,
    "factions": [
      "Sol",
      "Cent"
    ],
    "scan_min_x": -1500,
    "scan_max_x": 1500,
    "scan_min_z": -1500,
    "scan_max_z": 1500,
    "scan_step": 15,
    "grid_w": 201,
    "grid_h": 201
  },
  "TheMaw": {
    "extent": 1500,
    "image_size": 4096,
    "factions": [
      "Sol",
      "Cent"
    ],
    "scan_min_x": -1500,
    "scan_max_x": 1500,
    "scan_min_z": -1500,
    "scan_max_z": 1500,
    "scan_step": 15,
    "grid_w": 201,
    "grid_h": 201
  },
  "WhisperingPlains": {
    "extent": 2048,
    "image_size": 4096,
    "factions": [
      "Sol",
      "Cent"
    ],
    "scan_min_x": -2040,
    "scan_max_x": 2040,
    "scan_min_z": -2040,
    "scan_max_z": 2040,
    "scan_step": 15,
    "grid_w": 273,
    "grid_h": 273
  }
};
