// Auto-generated by preprocess.py — do not edit
const MAP_CONFIG = {
  "Badlands": {
    "extent": 3000,
    "image_size": 4096,
    "factions": [
      "Sol",
      "Cent"
    ]
  },
  "BlackIsle": {
    "extent": 1000,
    "image_size": 4096,
    "factions": [
      "Sol",
      "Cent"
    ],
    "scan_min_x": -990,
    "scan_max_x": 990,
    "scan_min_z": -990,
    "scan_max_z": 990,
    "scan_step": 15,
    "grid_w": 133,
    "grid_h": 133
  },
  "Citadel": {
    "extent": 1500,
    "image_size": 4096,
    "factions": [
      "Sol",
      "Cent"
    ],
    "scan_min_x": -1500,
    "scan_max_x": 1500,
    "scan_min_z": -1500,
    "scan_max_z": 1500,
    "scan_step": 15,
    "grid_w": 201,
    "grid_h": 201
  },
  "CrimsonPeak": {
    "extent": 2048,
    "image_size": 4096,
    "factions": [
      "Sol",
      "Cent"
    ]
  },
  "CrystalChasm": {
    "extent": 1500,
    "image_size": 4096,
    "factions": [
      "Sol",
      "Cent"
    ]
  },
  "GreatErg": {
    "extent": 3000,
    "image_size": 4096,
    "factions": [
      "Sol",
      "Cent"
    ]
  },
  "IndustrialQuarter": {
    "extent": 2000,
    "image_size": 4096,
    "factions": [
      "Sol",
      "Cent"
    ],
    "scan_min_x": -1995,
    "scan_max_x": 1995,
    "scan_min_z": -1995,
    "scan_max_z": 1995,
    "scan_step": 15,
    "grid_w": 267,
    "grid_h": 267
  },
  "MonumentValley": {
    "extent": 3000,
    "image_size": 4096,
    "factions": [
      "Sol",
      "Cent"
    ],
    "scan_min_x": -3000,
    "scan_max_x": 3000,
    "scan_min_z": -3000,
    "scan_max_z": 3000,
    "scan_step": 15,
    "grid_w": 401,
    "grid_h": 401
  },
  "NarakaCity": {
    "extent": 3000,
    "image_size": 4096,
    "factions": [
      "Sol",
      "Cent"
    ]
  },
  "NorthPolarCap": {
    "extent": 2048,
    "image_size": 4096,
    "factions": [
      "Sol",
      "Cent"
    ]
  },
  "RiftBasin": {
    "extent": 1500,
    "image_size": 4096,
    "factions": [
      "Sol",
      "Cent"
    ]
  },
  "TheMaw": {
    "extent": 1500,
    "image_size": 4096,
    "factions": [
      "Sol",
      "Cent"
    ]
  },
  "WhisperingPlains": {
    "extent": 2048,
    "image_size": 4096,
    "factions": [
      "Sol",
      "Cent"
    ]
  }
};
